### ISSUE TITLE
Installing CLI on Arch Linux with Snap

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#141]
When installing the cli with `sudo snap install enonic` on arch linux it has problems:
* It does not seem to like my java home: JAVA_HOME is set to an invalid directory
* It is unable to start service on port 8080
* The ~/.enonic folder does not appear but is is located at ~/snap/enonic/5/.enonic

When installing with `sudo snap install --devmode enonic`:
* Still complains about java home
* It is able to start the service on port 8080

When downloading the binary manually from the enonic repo and installing it has no problems.

The reason could be because goreleaser is releasing [the snap in strict mode](https://github.com/enonic/cli-enonic/blob/acf3357a236829c73bb0929a3c082df3efdbabc4/.goreleaser.yml#L253).

I am wondering if adding plugs to the `.goreleaser.yml` file would do the trick? Something like this:
```yaml
snapcraft:
  ...
  name: enonic
  ...
  confinement: strict

  apps:
    enonic:
      plugs: ["network", "network-bind", "personal-files", "system-files"]

  plugs:
    personal-files:
      read:
      - $HOME/.enonic
      write:
      - $HOME/.enonic
    system-files:
      read:
      - $JAVA_HOME
```

Links:
* [Snapcraft confinement](https://snapcraft.io/docs/reference/confinement)
* [Snapcraft supported interfaces](https://forum.snapcraft.io/t/supported-interfaces/7744)
* [Plugs in goreleaser](https://goreleaser.com/snapcraft/)
