### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by rymsha** [enonic/cli-enonic#267]
https://github.com/golang/go/wiki/Modules

**Comment by rymsha** [comment]
this would allow to turn on auto module updates

`.github/dependabot.yml`
```
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  assignees:
    - "pmi"
  reviewers:
    - "pmi"
```
